
# Elasticsearch defenition
elasticsearch:
    target:
      host: localhost
      port: 9200
      index: .monitor
      types:
        system: system
        stats: stats
    source:
      host: localhost
      port: 9200

#Scheduler defenition
scheduler:
  interval: 10s