
# Elasticsearch defenition
elasticsearch:
    target:
      host: localhost
      port: 9200
      index:
        name: .monitor
        #right now must be compitible with datetime.strftime and represent time appending to name of index
        dateformat: "%Y%m%d"
        # name of field that prefix node (by default elasticsearch node id not exactly usefull
        nodeprefix: host
        # will calculate differrence with last saved document and save number to elasticsearch
        delta:
        #   - jvm.gc.collectors.old.collection_count
        #   - indices.docs.count
      types:
        system: system
        stats: stats
    source:
      host: localhost
      port: 9200

#Scheduler defenition
scheduler:
  interval:
    #possible values second, minute, hour
    units: second
    value: 5

logging:
  #possible values DEBUG INFO WARN ERROR FATAL
  level: DEBUG