
# Elasticsearch defenition
elasticsearch:
    target:
      host: localhost
      port: 9200
      index:
        name: .monitor
        #right now must be compitible with datetime.strftime
        dateformat: "%Y%m%d"
      types:
        system: system
        stats: stats
    source:
      host: localhost
      port: 9200

#Scheduler defenition
scheduler:
  interval:
    #possible values second, minute, hour
    units: second
    value: 5

logging:
  #possible values DEBUG INFO WARN ERROR FATAL
  level: DEBUG