
elasticsearch:
  manager:
    host: localhost
    port: 9200
    index: .manager

manager:
  tasks:
    - task:
        name: First task
        debug: true
        interval:
          #possible values: seconds minutes hours
          units: seconds
          value: 10


logging:
  name: manager
     #possible values DEBUG INFO WARN ERROR FATAL
  level: DEBUG