
elasticsearch:
  manager:
    host: master
    port: 9200
    index: .manager

manager:
  tasks:
    - task:
        name: First task
        debug: true
        code: mng = Manager(task); mng.run_for_targets()
        interval:
          #possible values: seconds minutes hours
          units: minutes
          value: 12


logging:
  name: manager
     #possible values DEBUG INFO WARN ERROR FATAL
  level: DEBUG