
manager:
  tasks:
    - task:
        name: First task
        debug: true
        interval:
          #possible values: seconds minutes hours
          units: seconds
          value: 10
        elasticsearch:
          host: localhost
          port: 9200
          index: .manager


logging:
  name: manager
     #possible values DEBUG INFO WARN ERROR FATAL
  level: DEBUG