
elasticsearch:
  manager:
    host: localhost
    port: 9200
    index: .manager
  slaves:
    - cluster:
        host: localhost1
        port: 9200
        scheduler:
          interval: 5
          #possible values: seconds minutes hours
          units: seconds
    - cluster:
        host: localhost2
        port: 9200
        scheduler:
          interval: 10
          #possible values: seconds minutes hours
          units: seconds


logging:
  name: manager
     #possible values DEBUG INFO WARN ERROR FATAL
  level: DEBUG